before_install:
  - date
  - cat /proc/cpuinfo
  - cd ${HOME}
  - sudo apt-get -qq -y install libgmp-dev
  - export NUMCPU=`grep -c "^processor" < /proc/cpuinfo`
  # Setup emulation environment for Raspberry Pi
  - wget http://downloads.raspberrypi.org/raspbian_latest -O raspbian_latest.zip
  # Setup ARM cross toolchain
  - git clone https://github.com/raspberrypi/tools.git
  - export RASPI_PREFIX=${HOME}/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-
  - ${RASPI_PREFIX}gcc --version
  - gcc --version
  # Get ATS2
  - git clone https://github.com/githwxi/ATS-Postiats.git
  # Build ATS1
  - export ATSHOME=${HOME}/ats-lang-anairiats-0.2.11
  - export ATSHOMERELOC=ATS-0.2.11
  - ./ATS-Postiats/travis-ci/setup.sh 0.2.11
  # Build ATS2
  - export PATSHOME=${HOME}/ATS-Postiats
  - export PATSHOMERELOC=${PATSHOME}
  - export PATH=${PATH}:${PATSHOME}/bin
  - cd ${PATSHOME} && make -f codegen/Makefile_atslib && make -f Makefile_devl src_depend && make -f Makefile_devl all
  - patsopt --version
script:
  - cd ${TRAVIS_BUILD_DIR}
  - make -j ${NUMCPU}
after_script:
  - date
