before_install:
  - date
  - cat /proc/cpuinfo
  - sudo apt-get -qq -y install libgc-dev libgmp-dev make bc
  - export NUMCPU=`grep -c "^processor" < /proc/cpuinfo`
  # Setup ARM cross toolchain
  - cd ${HOME}
  - git clone https://github.com/raspberrypi/tools.git
  - export RASPI_PREFIX=${HOME}/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-
  - ${RASPI_PREFIX}gcc --version
  - gcc --version
  # Seting-up ATS2-contrib
  - cd ${HOME}
  - git clone https://github.com/githwxi/ATS-Postiats-contrib.git
  - export PATSHOMERELOC=${HOME}/ATS-Postiats-contrib
  # Building ATS2
  - cd ${HOME}
  - git clone git://git.code.sf.net/p/ats2-lang/code ATS2-srcfrg
  - export PATSHOME=${HOME}/ATS2-srcfrg
  - export PATH=${PATH}:${PATSHOME}/bin
  - cd ${PATSHOME} && ./configure && make -j ${NUMCPU}
  - patsopt --version
script:
  - cd ${TRAVIS_BUILD_DIR}
  - make -j ${NUMCPU} | grep -v ' CC '
after_script:
  - date
